# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json

site_name: My Little C Library
repo_url: https://github.com/cydaw6/MyLittleCLibrary
copyright: Copyright &copy; 2022 Antoine Bastos

nav:
  - Home: 'index.md'
  - 'Data structures':
    - Lists:
        - 'data-structures/List/index.md'
        - 'data-structures/List/array-list.md'
        - 'data-structures/List/linked-list.md'
        - 'data-structures/List/circular-linked-list.md'
        - 'data-structures/List/double-linked-list.md'
        - 'data-structures/List/circular-double-linked-list.md'
    - Trees:
        - 'data-structures/Tree/index.md'
        - 'data-structures/Tree/binary-search-tree.md'
        - 'data-structures/Tree/avl-tree.md'
        - 'data-structures/Tree/ternary-search-tree.md'
        - 'data-structures/Tree/bk-tree.md'
        -
    - Types: 'data-structures/types.md'
  - 'Extended examples': 'extended-examples.md'
  - Implementation: 'implementation.md'

markdown_extensions:
  - toc:
      permalink: "#"


  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

plugins:
  - search:
      lang: en

theme:
  name: material
  font:
    code: Roboto Mono
  icon:
    logo: material/book
    repo: fontawesome/brands/github
  favicon: images/favicon.png
  palette:
    scheme: slate
    primary: deep purple
    accent: light blue
  features:
    - header.autohide
    - navigation.tracking
    - navigation.top
    - navigation.indexes
# - toc.integrate
