# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json

site_name: My Little C Library
repo_name: cydaw6/MyLittleCLibrary
repo_url: https://github.com/cydaw6/MyLittleCLibrary
copyright: Copyleft 🄯 2022 Antoine Bastos - Apache-2.0 license

nav:
  - Home: 'index.md'
  - Download: 'download.md'
  - Installation: 'installation.md'
  - 'Data structures':
    - Lists:
        - 'data-structures/List/index.md'
        - 'data-structures/List/array-list.md'
        - 'data-structures/List/linked-list.md'
        - 'data-structures/List/circular-linked-list.md'
        - 'data-structures/List/double-linked-list.md'
        - 'data-structures/List/circular-double-linked-list.md'
    - Trees:
        - 'data-structures/Tree/index.md'
        - 'data-structures/Tree/binary-search-tree.md'
        - AVL Tree: 'data-structures/Tree/avl-tree.md'
        - 'data-structures/Tree/ternary-search-tree.md'
        - BK Tree: 'data-structures/Tree/bk-tree.md'
    - Types: 'data-structures/types.md'
  - 'Extended examples': 'extended-examples.md'
  - Implementation: 'implementation.md'
  - Credits: 'credits.md'

markdown_extensions:
  - toc:
      permalink: "#"
  - mkdocs_graphviz:
      light_theme: 000000      # Any HTML Color Name or any HTML Hexadecimal color code WITHOUT the `#` sign
      dark_theme: FFFFFF       # Any HTML Color Name or any HTML Hexadecimal color code WITHOUT the `#` sign
      color: 789ABC            # Any HTML Color Name or any HTML Hexadecimal color code WITHOUT the `#` sign
      bgcolor: none            # Any HTML Color Name or any HTML Hexadecimal color code WITHOUT the `#` sign
      graph_color: 789ABC      # Any HTML Color Name or any HTML Hexadecimal color code WITHOUT the `#` sign
      graph_fontcolor: 789ABC  # Any HTML Color Name or any HTML Hexadecimal color code WITHOUT the `#` sign
      node_color: 789ABC       # Any HTML Color Name or any HTML Hexadecimal color code WITHOUT the `#` sign
      node_fontcolor: 789ABC   # Any HTML Color Name or any HTML Hexadecimal color code WITHOUT the `#` sign
      edge_color: 789ABC       # Any HTML Color Name or any HTML Hexadecimal color code WITHOUT the `#` sign
      edge_fontcolor: 789ABC   # Any HTML Color Name or any HTML Hexadecimal color code WITHOUT the `#` sign
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true

extra_javascript:
  - https://cdn.jsdelivr.net/gh/rod2ik/cdn@main/mkdocs/javascripts/massilia-graphviz.js

plugins:
  - search:
      lang: en

theme:
  name: material
  font:
    code: Roboto Mono
  icon:
    logo: material/book
    repo: fontawesome/brands/github
  favicon: images/favicon.png
  palette:
    # Palette toggle for light mode
    - scheme: default
      primary: deep purple
      accent: deep purple
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      primary: deep purple
      accent: deep purple
      toggle:
        icon: material/brightness-3
        name: Switch to light mode
  features:
    - header.autohide
    - navigation.tracking
    - navigation.top
    - navigation.indexes
    - content.tabs.link
# - toc.integrate