# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json

site_name: My Little C Library
repo_url: https://github.com/cydaw6/MyLittleCLibrary

nav:
  - Home: 'index.md'
  - 'Data structures':
    - Lists: 'data-structures/lists.md'
    - Trees: 'data-structures/trees.md'
    - Types: 'data-structures/types.md'
  - 'Extended examples': 'extended-examples.md'
  - Implementation: 'implementation.md'

markdown_extensions:
  - toc:
      permalink: "#"


  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

plugins:
  - search:
      lang: en

theme:
  name: material
  font:
    code: Roboto Mono
  icon:
    logo: material/book
    repo: fontawesome/brands/github
  favicon: images/favicon.png
  palette:
    scheme: slate
    primary: deep purple
    accent: light blue
  features:
    - header.autohide
    - navigation.tracking
#    - toc.integrate
